/*
 * Gmail Gold Important Marker — content.js
 * =========================================
 * Local, visual-only content script for https://mail.google.com/*.
 *
 * What this script does:
 *  - Reads user preferences from chrome.storage.sync (enabled, which
 *    features are on, and the chosen gold color).
 *  - Sets a few classes/CSS custom properties on <html> that content.css
 *    uses to recolor Gmail's Important-marker and/or Star icons.
 *  - Tags the specific marker/star icon elements it finds with extension-
 *    owned classes (ggim-important-marker / ggim-star) so content.css can
 *    target exactly those elements.
 *  - Watches for Gmail's single-page-app DOM updates (new rows scrolling
 *    in, navigating between Inbox/Search/Labels, etc.) with a debounced
 *    MutationObserver, and re-syncs the tagged elements.
 *
 * What this script never does:
 *  - Read, store, or transmit email subjects, senders, recipients, bodies,
 *    labels, or any other message content/metadata.
 *  - Make any network request. (There are none in this file at all.)
 *  - Call Gmail/Google APIs.
 *  - Use eval/new Function or load any remote code.
 *  - Modify anything other than CSS-visible presentation of two small
 *    icon elements.
 *
 * SELECTOR COMPATIBILITY LAYER
 * -----------------------------
 * Gmail's own CSS class names are generated by a build tool and are not
 * stable across releases, so this script intentionally avoids depending
 * on them as the *primary* signal. Instead it keys off the accessible
 * name Gmail assigns for screen readers (`aria-label`), which is required
 * for accessibility and changes far less often. Every selector lives in
 * the single SELECTORS object below so the whole compatibility layer can
 * be updated in one place if Gmail changes its markup.
 *
 * VERIFIED LIVE 2026-09-28 against a real, signed-in Gmail inbox
 * (English UI, current "gm3" Gmail build) via DevTools:
 *  - Important marker container: a `role="switch"` element (currently a
 *    `<div class="pG">`) whose `aria-label` starts with "Important" in
 *    the marked-as-important state. IMPORTANT: Gmail generates several
 *    different explanation strings depending on *why* it thinks a
 *    message is important — confirmed variants include "Important
 *    according to Google magic." and "Important because previous
 *    messages in the conversation were important.", and Gmail's ML
 *    ranker can produce others (e.g. per-sender reasons) not seen during
 *    this session. Matching the exact string missed most of these and
 *    left some Important markers un-recolored — so the selector below
 *    matches on the "Important" *prefix* instead of one fixed sentence.
 *    The unmarked state's label is "Not important", which does not share
 *    that prefix, so this stays state-safe. A left-nav "Important" label
 *    link also exists (`aria-label="Important"`) but has no `role`
 *    attribute at all, so requiring `role="switch"` excludes it.
 *    The actual painted icon is a nested element (currently
 *    `div.pH.Uieduc.a9q`) whose own `background-image` is a
 *    Google-hosted PNG (`.../label_important_fill_baseline_p200_20dp.png`)
 *    — i.e. Case B (filter fallback) in content.css, not inline SVG.
 *  - Star: a `role="button"` element (currently `<span class="T-KT ...">`)
 *    whose `aria-label` is exactly "Starred" for the filled/true state —
 *    unlike the importance marker, this was confirmed to be a plain
 *    boolean with no per-message variants, so an exact match is used.
 *    The icon is painted via a `::before` pseudo-element background-image
 *    (`.../star_fill_baseline_p200_20dp.png`) on that same span, also
 *    Case B. On the account used for verification the star already
 *    rendered natively gold (not blue), which is why "Recolor Stars"
 *    defaults to off — it's only needed for accounts on a Gmail rollout
 *    where the star has also gone blue.
 *  - `pG` / `T-KT` and friends are exactly the kind of short, generated
 *    class names described above: they are NOT used as selectors here,
 *    only `aria-label` (plus `role` for the important-marker prefix
 *    match) is, since class names alone don't distinguish state.
 *
 * These strings/prefixes can still change without notice on any future
 * Gmail release or A/B rollout, and non-English Gmail UI languages use
 * translated label text not covered here — re-verify with DevTools
 * (see README "Selector verification") before every release, and add
 * translated strings to SELECTORS if you use Gmail in another language.
 */

(function () {
  'use strict';

  var DEFAULTS = {
    enabled: true,
    recolorMarkers: true,
    recolorStars: false,
    goldColor: '#f4b400'
  };

  var STATE = {
    enabled: DEFAULTS.enabled,
    recolorMarkers: DEFAULTS.recolorMarkers,
    recolorStars: DEFAULTS.recolorStars,
    goldColor: DEFAULTS.goldColor
  };

  // === Selector compatibility layer =====================================
  // See the header comment above for how/when these were verified. Update
  // this object, nothing else, if Gmail's DOM or wording changes.
  var SELECTORS = {
    // The "important" marker container, in its marked-as-important (true)
    // state only — the unmarked state ("Not important") is left at
    // Gmail's native color. Gmail generates several different reason
    // strings for the true state (all confirmed to start with the word
    // "Important" — see header comment), so this matches that prefix
    // rather than one fixed sentence. Restricting to role="switch"
    // excludes the unrelated left-nav "Important" label link, which
    // shares the word but not the role.
    importantMarker: [
      '[role="switch"][aria-label^="Important" i]'
    ],
    // The star container, in its starred (true) state only — the
    // unstarred outline icon is left at Gmail's native color. Confirmed
    // to be a plain boolean (no per-message variants), so this is an
    // exact match, scoped to role="button" for the same reason as above.
    star: [
      '[role="button"][aria-label="Starred" i]'
    ]
  };

  var MARKER_CLASS = 'ggim-important-marker';
  var STAR_CLASS = 'ggim-star';
  var FILTER_CLASS = 'ggim-use-filter';

  var scanTimer = null;
  var observer = null;
  var observing = false;

  // === Color helpers ======================================================

  function isValidHex(hex) {
    return typeof hex === 'string' && /^#[0-9a-fA-F]{6}$/.test(hex);
  }

  function hexToRgb(hex) {
    var v = parseInt(hex.slice(1), 16);
    return { r: (v >> 16) & 255, g: (v >> 8) & 255, b: v & 255 };
  }

  function rgbToHsl(r, g, b) {
    r /= 255; g /= 255; b /= 255;
    var max = Math.max(r, g, b), min = Math.min(r, g, b);
    var h = 0, s = 0, l = (max + min) / 2;
    var d = max - min;
    if (d !== 0) {
      s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
      switch (max) {
        case r: h = (g - b) / d + (g < b ? 6 : 0); break;
        case g: h = (b - r) / d + 2; break;
        case b: h = (r - g) / d + 4; break;
      }
      h *= 60;
    }
    return { h: h, s: s, l: l };
  }

  // Builds an approximate CSS filter() chain that pushes a neutral/blue
  // sprite icon toward the requested gold hue. This is a best-effort
  // approximation (filters can't reproduce an exact hex on top of
  // arbitrary source pixels), used for the Case B path in content.css.
  // As of the live verification noted above, Case B is actually the
  // *common* path today — both the Important marker and the Starred
  // icon are currently painted as Google-hosted PNG sprites (via
  // background-image / ::before), not inline SVG or CSS mask — so this
  // formula was tuned by visually checking its output against Gmail's
  // real icons rather than treated as a rare fallback.
  function buildFilterFor(hex) {
    var rgb = hexToRgb(hex);
    var hsl = rgbToHsl(rgb.r, rgb.g, rgb.b);
    var hueRotate = Math.round(hsl.h) - 45; // empirical offset from sepia()'s base hue
    var saturate = Math.max(1.5, Math.min(8, (hsl.s * 6) + 1));
    var brightness = 0.75 + hsl.l * 0.5;
    return 'grayscale(1) sepia(1) saturate(' + saturate.toFixed(2) + ') ' +
      'hue-rotate(' + hueRotate + 'deg) brightness(' + brightness.toFixed(2) + ')';
  }

  // === Applying state to the page =========================================

  function applyRootState() {
    var root = document.documentElement;
    if (!root) return;
    var gold = isValidHex(STATE.goldColor) ? STATE.goldColor : DEFAULTS.goldColor;
    root.classList.toggle('ggim-enabled', !!STATE.enabled);
    root.classList.toggle('ggim-markers-on', !!STATE.recolorMarkers);
    root.classList.toggle('ggim-stars-on', !!STATE.recolorStars);
    root.style.setProperty('--ggim-gold', gold);
    root.style.setProperty('--ggim-filter', buildFilterFor(gold));
  }

  // Given the element matched by SELECTORS (the aria-labeled container),
  // finds the actual element whose pixels need recoloring, and decides
  // which content.css case applies. Gmail has been observed to paint
  // these icons in more than one way even within the same build (see
  // header comment), so this checks, in order of preference:
  //   1. an inline <svg> descendant            -> exact color (Case A)
  //   2. a CSS mask-image on the container/descendant -> exact color (Case A)
  //   3. an <img> descendant                   -> filter fallback (Case B)
  //      (an <img> has no `fill`/mask/background-color to override)
  //   4. a background-image on the container/descendant itself -> filter (Case B)
  //   5. a background-image painted via a ::before pseudo-element on the
  //      container/descendant -> filter (Case B); CSS `filter` on an
  //      element also recolors its own ::before content.
  // Returns { el, useFilter } for the element to tag, or null if nothing
  // paintable was found (leaves the container untouched rather than
  // guessing).
  function resolveIconTarget(container) {
    try {
      var svg = container.querySelector('svg');
      if (svg) return { el: svg, useFilter: false };

      var nodes = [container];
      var descendants = container.querySelectorAll('*');
      for (var i = 0; i < descendants.length; i++) nodes.push(descendants[i]);

      for (var a = 0; a < nodes.length; a++) {
        var maskCs = window.getComputedStyle(nodes[a]);
        var mask = maskCs.maskImage || maskCs.webkitMaskImage;
        if (mask && mask !== 'none') return { el: nodes[a], useFilter: false };
      }

      for (var b = 0; b < nodes.length; b++) {
        if (nodes[b].tagName === 'IMG') return { el: nodes[b], useFilter: true };
      }

      for (var c = 0; c < nodes.length; c++) {
        var bgCs = window.getComputedStyle(nodes[c]);
        if (bgCs.backgroundImage && bgCs.backgroundImage !== 'none') {
          return { el: nodes[c], useFilter: true };
        }
      }

      for (var d = 0; d < nodes.length; d++) {
        var beforeCs = window.getComputedStyle(nodes[d], '::before');
        if (beforeCs.backgroundImage && beforeCs.backgroundImage !== 'none') {
          return { el: nodes[d], useFilter: true };
        }
      }
    } catch (err) {
      // Never let a styling probe break Gmail; just skip this element.
    }
    return null;
  }

  function queryAll(root, selectors) {
    var found = [];
    for (var i = 0; i < selectors.length; i++) {
      try {
        var nodes = root.querySelectorAll(selectors[i]);
        for (var j = 0; j < nodes.length; j++) found.push(nodes[j]);
      } catch (err) {
        // Selector unsupported/invalid in this Gmail build — skip it.
      }
    }
    return found;
  }

  // Idempotently syncs `className` onto the resolved icon element for
  // every container currently matching `selectors` (when `active`), and
  // removes it from any previously tagged element that no longer matches
  // (e.g. a star that was just un-starred in place, or scrolled out and
  // replaced by a different row). Bounded to `root`, a small, already-
  // loaded subtree, so this never touches message bodies or off-screen
  // content.
  function syncGroup(root, selectors, className, active) {
    var containers = active ? queryAll(root, selectors) : [];
    var targets = [];
    for (var i = 0; i < containers.length; i++) {
      var resolved = resolveIconTarget(containers[i]);
      if (resolved) targets.push(resolved);
    }
    var targetSet = new Set(targets.map(function (t) { return t.el; }));

    for (var j = 0; j < targets.length; j++) {
      var el = targets[j].el;
      if (!el.classList.contains(className)) {
        el.classList.add(className);
      }
      el.classList.toggle(FILTER_CLASS, targets[j].useFilter);
    }

    var tagged = root.querySelectorAll('.' + className);
    for (var k = 0; k < tagged.length; k++) {
      var t = tagged[k];
      if (!targetSet.has(t)) {
        t.classList.remove(className, FILTER_CLASS);
      }
    }
  }

  function scan() {
    var root = document.body;
    if (!root) return;
    if (!STATE.enabled) {
      // Fully neutralize: strip every tag we've ever added so nothing
      // lingers even if a toggle is flipped back on later mid-session.
      syncGroup(root, [], MARKER_CLASS, false);
      syncGroup(root, [], STAR_CLASS, false);
      return;
    }
    syncGroup(root, SELECTORS.importantMarker, MARKER_CLASS, !!STATE.recolorMarkers);
    syncGroup(root, SELECTORS.star, STAR_CLASS, !!STATE.recolorStars);
  }

  function scheduleScan() {
    if (scanTimer) return;
    scanTimer = setTimeout(function () {
      scanTimer = null;
      try {
        scan();
      } catch (err) {
        // Fail silently and locally — never surface errors into Gmail's UI,
        // and never log anything that could contain email data (we only
        // ever touch icon elements, never message content, so this is
        // safe even if it did log).
      }
    }, 200);
  }

  function startObserving() {
    if (observing || !document.body) return;
    observer = new MutationObserver(function () {
      scheduleScan();
    });
    observer.observe(document.body, {
      childList: true,
      subtree: true,
      attributes: true,
      attributeFilter: ['aria-label', 'data-tooltip', 'class']
    });
    observing = true;
  }

  // === Preferences =========================================================

  function loadAndApply() {
    try {
      chrome.storage.sync.get(DEFAULTS, function (items) {
        if (chrome.runtime.lastError) return;
        STATE.enabled = !!items.enabled;
        STATE.recolorMarkers = !!items.recolorMarkers;
        STATE.recolorStars = !!items.recolorStars;
        STATE.goldColor = isValidHex(items.goldColor) ? items.goldColor : DEFAULTS.goldColor;
        applyRootState();
        scheduleScan();
        startObserving();
      });
    } catch (err) {
      // chrome.storage unavailable (e.g. extension context invalidated
      // mid-navigation) — leave Gmail exactly as-is.
    }
  }

  try {
    chrome.storage.onChanged.addListener(function (changes, area) {
      if (area !== 'sync') return;
      var relevant = false;
      ['enabled', 'recolorMarkers', 'recolorStars', 'goldColor'].forEach(function (key) {
        if (Object.prototype.hasOwnProperty.call(changes, key)) {
          relevant = true;
          STATE[key] = changes[key].newValue;
        }
      });
      if (!relevant) return;
      if (!isValidHex(STATE.goldColor)) STATE.goldColor = DEFAULTS.goldColor;
      applyRootState();
      scheduleScan();
    });
  } catch (err) {
    // Storage change notifications unavailable — preferences will still
    // apply on next page load via loadAndApply().
  }

  loadAndApply();
})();
